services:
    app:
        image: php:8.4-fpm
        container_name: trips_laravel_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - laravel_network

    web:
        image: nginx:latest
        container_name: trips_laravel_web
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel_network

    db:
        image: mysql:8.0
        container_name: trips_laravel_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: trips_laravel_api
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: trips_laravel_api
            MYSQL_PASSWORD: trips_laravel_api
        ports:
            - "3308:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge

volumes:
    db_data:
